### ISSUE TITLE
options for number of issues or filters for `list`

### ISSUE THREAD

**Issue by operte** [timvink/doing-cli#28]
What about having an option on `list` to only show the X most recent issues/PRs instead of the whole list? And/or allowing to apply some filters, like assignee or type. Something like:

```bash
doing list --recent 10
doing list --author "john jane.doe@email.com"
doing list --type "task bug"
doing list --status active
````

The author filter could use the defaults that we will [eventually add](https://github.com/timvink/doing-cli/issues/14) to the config file. 

Some of these options could also be set as defaults on the config file (for example, if I don't want to see User Stories, just Tasks and Bugs; or if I want to include Resolved tasks, which are hidden by default at the moment).

**Comment by timvink** [comment]
I figured this issue would pop up. It makes most sense to mimic the github-cli of [`gh issue list`](https://cli.github.com/manual/gh_issue_list), for consistency. Which is:

```shell
  -a, --assignee string    Filter by assignee
  -A, --author string      Filter by author
  -l, --label strings      Filter by labels
  -L, --limit int          Maximum number of issues to fetch (default 30)
      --mention string     Filter by mention
  -m, --milestone number   Filter by milestone number or `title`
  -s, --state string       Filter by state: {open|closed|all} (default "open")
  -w, --web                Open the browser to list the issue(s)
```

You can already overwrite defaults of commands using environment variables (see https://timvink.github.io/doing-cli/reference/config_file/), would make sense to also allow for setting these env vars in the config file, for full flexibility.

**Comment by timvink** [comment]
So far implemented

```
  -a, --assignee string    Filter by assignee
  -A, --author string      Filter by author
  -l, --label strings      Filter by labels
```

Will not implement:

- ` -L, --limit int          Maximum number of issues to fetch (default 30)` - You cannot set any limits in the work item query language [source](https://stackoverflow.com/questions/14282712/how-to-use-limit-keyword-as-using-in-ms-sql-by-wiql-to-query-tfs-workitem).
- `-m, --milestone number   Filter by milestone number or title`. I will have to use a range of successive queries to do this. Too much work for what's probably an edge case
 
To do:

```
  -s, --state string       Filter by state: {open|closed|all} (default "open")
  -w, --web                Open the browser to list the issue(s)
```
