### ISSUE TITLE
Allow overwriting default options in command via config file 

### ISSUE THREAD

**Issue by timvink** [timvink/doing-cli#29]
Originally discussed in #28 : You can already overwrite defaults of commands using environment variables (see https://timvink.github.io/doing-cli/reference/config_file/), it would make sense to also allow for setting these env vars in the config file, for full flexibility.

Order then should be: explicitly set values > environment variables > config file > the default value.

**Comment by operte** [comment]
Good one. I think this is much better than having to set environment variables.

**Comment by timvink** [comment]
Will be released prob. tomorrow in `v0.8`
