### ISSUE TITLE
Exotic characters in branch names causes an error on create pr

### ISSUE THREAD

**Issue by PaulHofma** [timvink/doing-cli#32]
Currently, exotic characters in branch names (in the case I tested specifically, it was parentheses) will cause an error on `doing create pr` or `doing workon` in the checkout step, due to the branch name being passed directly rather than between quotes. 

That is, it is passed as 
`git checkout -b branch_name` 
rather than
`git checkout -b "branch_name"`

Suggested fix would be to provide the branch name in between quotes as above - this should not cause different edge cases to pop up, but will fix this bug.

**Comment by timvink** [comment]
Thanks for reporting!

Indeed, as we create branchnames out of issue titles, we might get weird characters like parenthesis. I'll release a quick fix with the quotes soon.

A better approach might be improving our 'issue title to branchname' approach, from a simple 'replace spaces with underscores' to a more complex '.. and remove all punctuation'. 

Something like:

```python
import string
import re

my_str = "My issue! ~ solves #12 \--/ :)"

chars = re.escape(string.punctuation)
new_str = print(re.sub(r'['+chars+']', '',my_str))
new_str 
# 'My issue  solves 12' 

from doing.utils import to_snake_case
to_snake_case(new_str)
# ''my_issue__solves_12__'
```

**Comment by PaulHofma** [comment]
Ah yes, now that you mention it, that does actually sound like a better long-term solution! Since the current solution _also_ means one would need to use quotations when checking out the branch manually (obviously). That seems a bit cumbersome long-term ^^; Nice!

**Comment by timvink** [comment]
Fixed in https://github.com/timvink/doing-cli/releases/tag/v0.6.1
